language: node_js
node_js:
- '0.11'
- '0.10'
notifications:
  slack:
    secure: esKBfmWQDALSIPcQ++1HELpJL0CX3v7xc56Vz3KVLAS/7IWve5WWivjLamBqi4TWqGqJjU3lAYtSrDAX4fwtUK6yZRWVbz12xFPAnO+GHWXkxgSMYkNnR3V/PML6NokCLaJGtwZnYPJFl2BZdJDlcJEyni8CnRYNSSHH4FKlMiI=
