# Name of the redis queue to listen to
queue: phoenix
request:
  url: "http://me.captnemo.in/"
  # This is only for POST, PATCH, PUT requests
  body: "This is the complete body that you wish to send"
  data:
    this: is
    an: object
    which: will
    be: serialized
  # This is the query string appended to the url
  query:
    phantom: 1
  # removes the referer header when a redirect happens
  removeRefererHeader: false
  #In case you want to send a json body
  #This is automatically serialized and adds the content type headers for json
  json:
    a: b
  # This is just basic auth
  auth:
    username: username
    password: password
  headers:
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    Accept-Encoding: gzip, deflate, sdch
    Accept-Language: en-US,en;q=0.8,hi;q=0.6,sv;q=0.4
    Cache-Control: max-age=0
    Connection: keep-alive
    DNT: 1
    User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2342.2 Safari/537.36
# This is custom js to run in the proper context on the webpage _before_ it loads
js: custom.js
