request:
	method: GET
	qs: []
	# removes the referer header when a redirect happens
	removeRefererHeader: false
	headers:
		Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
		Accept-Language: en-US,en;q=0.8,hi;q=0.6,sv;q=0.4
		Cache-Control: max-age=0
		Connection: keep-alive
		DNT: 1
		# Top one at https://techblog.willshouse.com/2012/01/03/most-common-user-agents/
		# As on 26 Mar 2015
		User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36
# This is custom js to run in the proper context on the webpage _before_ it loads
js: custom.js